<?php

/**
 * Implements hook_help().
 */
function tims_help($path, $arg) {
  switch ($path) {
    case 'admin/help#tims':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The TIMS module allows users with the <em>Administer site configuration</em> permission to create content templates within the browser using the Twig templating language.') . '</p>';
      $output .= '<h3>' . t('Naming your templates') . '</h3>';
      $output .= '<p>' . t('Naming convention is based on what is contained in the theme_get_suggestions array. For example, if you would like to template a node of the article content type, instead of creating a php file named <em>node--article.tpl.php</em> you will create a template in this module\'s interface called <em>node__article</em>. See <a href="@link">Working with template suggestions</a> for more about working with template suggestions and their naming convention.', array('@link' => url('https://drupal.org/node/223440'))) . '</p>';
      $output .= '<h3>' . t('Twig syntax') . '</h3>';
      $output .= '<p>' . t('For a guide to the Twig syntax, refer to the <a href="@link">documention for theming Drupal 8</a> which uses Twig for theming as part of core.', array('@link' => url('https://drupal.org/node/1906384'))) . '</p>';
      $output .= '<h3>' . t('Differences between Drupal 8 theming and this module') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Printing a variable') . '</dt>';
      $output .= '<dd>' . t('Drupal 8 Twig syntax needs to modified when printing a variable. The variable needs to wrapped in the render function and the raw filter must be applied.') . '</dd>';
      $output .= '<dd>' . t('Render the body field:');
      $output .= '<br />' . t('Drupal 7 TIMS Module: ') . '{{ render(content.body)|raw }}';
      $output .= '<br />' . t('Drupal8: ') . '{{ content.body }}' . '</dd>';
      $output .= '</dl>';
      return $output;
  }
}

/**
 * Implements hook_init().
 */
function tims_init() {
  // We need to register our stuff after everything else, this is a bit of a hack to do so.
  theme_get_registry();
  $theme_registry_object = theme_get_registry(FALSE);
  $tmp = &drupal_static('theme_get_registry');
  $theme_registry_array = $tmp[1];

  foreach (variable_get('tims_templates', array()) as $name => $template) {
    $theme_registry_object[$name] =
    $theme_registry_array[$name] = array(
      'function' => 'tims_render',
      'variables' => array('template' => $name),
      'theme path' => drupal_get_path('module', 'tims') . '/theme',
      'type' => 'module',
    );
  }
}

/**
 * Renders a template using Twig.
 */
function tims_render($variables) {
  require_once DRUPAL_ROOT . '/sites/all/libraries/Twig/lib/Twig/Autoloader.php';
  Twig_Autoloader::register();
  require_once drupal_get_path('module', 'tims') . '/tims_extension.php';

  $templates = variable_get('tims_templates', array());
  $template = '';
  foreach (array_reverse($variables['theme_hook_suggestions']) as $hook) {
    if (array_key_exists($hook, $templates)) {
      $template = $templates[$hook];
      break;
    }
  }

  if (!$template) {
    return;
  }

  $loader = new Twig_Loader_String();
  $twig = new Twig_Environment($loader);
  $twig->addExtension(new Tims_Extension());
  return $twig->render($template, $variables);
}

/**
 * Implements hook_menu().
 */
function tims_menu() {
  $items = array();

  $items['admin/structure/tims'] = array(
    'title' => 'Twig templates',
    'description' => 'Manage content templates using the Twig templating engine.',
    'access callback' => TRUE,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tims_list'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'tims.admin.php',
  );
  $items['admin/structure/tims/create'] = array(
    'title' => 'Create template',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tims_edit', '_new_'),
    'access callback' => TRUE,
    'type' => MENU_LOCAL_ACTION,
    'file' => 'tims.admin.php',
  );
  $items['admin/structure/tims/%/edit'] = array(
    'title' => 'Edit template',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tims_edit', 3),
    'access callback' => TRUE,
    'file' => 'tims.admin.php',
  );
  $items['admin/structure/tims/%/delete'] = array(
    'title' => 'Delete template',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tims_delete', 3),
    'access callback' => TRUE,
    'file' => 'tims.admin.php',
  );

  return $items;
}
