<?php

/**
 * Implements hook_help().
 */
function tims_help($path, $arg) {
  switch ($path) {
    case 'admin/help#tims':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The TIMS module allows users with the <em>Administer site configuration</em> permission to create content templates within the browser using the Twig templating language.') . '</p>';
      $output .= '<h3>' . t('Naming your templates') . '</h3>';
      $output .= '<p>' . t('Naming convention is based on what is contained in the theme_get_suggestions array. For example, if you would like to template a node of the article content type, instead of creating a php file named <em>node--article.tpl.php</em> you will create a template in this module\'s interface called <em>node__article</em>. See <a href="@link">Working with template suggestions</a> for more about working with template suggestions and their naming convention.', array('@link' => url('https://drupal.org/node/223440'))) . '</p>';
      $output .= '<h3>' . t('Twig syntax') . '</h3>';
      $output .= '<p>' . t('For a guide to the Twig syntax, refer to the <a href="@link">documention for theming Drupal 8</a> which uses Twig for theming as part of core.', array('@link' => url('https://drupal.org/node/1906384'))) . '</p>';
      $output .= '<h3>' . t('Differences between Drupal 8 theming and this module') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Printing a field') . '</dt>';
      $output .= '<dd>' . t('Drupal 8 Twig syntax needs to modified when printing a field. The variable needs to wrapped in the render function and the raw filter must be applied.') . '</dd>';
      $output .= '<dd>' . t('Render the body field:');
      $output .= '<br />' . t('Drupal 7 TIMS Module: ') . '{{ render(content.body)|raw }}';
      $output .= '<br />' . t('Drupal8: ') . '{{ content.body }}' . '</dd>';
      $output .= '<dd>' . t('Note that printing metadata such as the title or nid works as expected: ') . '{{ title }}' . '</dd>';
      $output .= '</dl>';
      return $output;
  }
}

/**
 * Implements hook_init().
 */
function tims_init() {
  // We need to register our stuff after everything else, this is a bit of a hack to do so.
  theme_get_registry();
  $theme_registry_object = theme_get_registry(FALSE);
  $tmp = &drupal_static('theme_get_registry');
  $theme_registry_array = $tmp[1];

  foreach (variable_get('tims_templates', array()) as $hook => $template) {
    $info = array();
    if (isset($theme_registry_array[$hook])) {
      $safeKeys = array('type', 'render element', 'preprocess functions', 'process functions', 'variables');
      $info = array_intersect_key($theme_registry_array[$hook], array_flip($safeKeys));
    }

    $info['function'] = 'tims_render';
    $info['theme path'] = drupal_get_path('module', 'tims') . '/theme';
    $info['process functions'][] = 'tims_set_template';

    $theme_registry_object[$hook] = $theme_registry_array[$hook] = $info;
  }
}

/**
 * @param $variables
 * @param $hook
 *
 * Implementation of template_process.
 * Used to determine which TWIG template to use when rendering the element.
 */
function tims_set_template(&$variables, $hook) {
  $variables['#tims_template'] = $hook;
}

/**
 * Renders a template using Twig.
 */
function tims_render($variables) {
  require_once DRUPAL_ROOT . '/sites/all/libraries/Twig/lib/Twig/Autoloader.php';
  Twig_Autoloader::register();
  require_once drupal_get_path('module', 'tims') . '/tims_extension.php';

  $templates = variable_get('tims_templates', array());

  $template = NULL;
  if (isset($variables['#tims_template'])) {
    $hook = $variables['#tims_template'];
    if (isset($templates[$hook])) {
      $template = $templates[$hook];
    }
  }

  foreach (array_reverse($variables['theme_hook_suggestions']) as $hook) {
    if (array_key_exists($hook, $templates)) {
      $template = $templates[$hook];
      break;
    }
  }

  if (!$template) {
    watchdog('tims', 'Unable to find the correct TWIG Template for a hooked element.', array(), WATCHDOG_ERROR);
    return;
  }

  $loader = new Twig_Loader_String();
  $twig = new Twig_Environment($loader, array(
    'debug' => true,
  ));
  $twig->addExtension(new Twig_Extension_Debug());
  $twig->addExtension(new Tims_Extension());
  return $twig->render($template, $variables);
}

/**
 * Implements hook_menu().
 */
function tims_menu() {
  $items = array();

  $items['admin/structure/tims'] = array(
    'title' => 'Twig templates',
    'description' => 'Manage content templates using the Twig templating engine.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tims_list'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'tims.admin.php',
  );
  $items['admin/structure/tims/create'] = array(
    'title' => 'Create template',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tims_edit', '_new_'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'tims.admin.php',
  );
  $items['admin/structure/tims/%/edit'] = array(
    'title' => 'Edit template',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tims_edit', 3),
    'access arguments' => array('administer site configuration'),
    'file' => 'tims.admin.php',
  );
  $items['admin/structure/tims/%/delete'] = array(
    'title' => 'Delete template',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tims_delete', 3),
    'access arguments' => array('administer site configuration'),
    'file' => 'tims.admin.php',
  );

  return $items;
}
